import 'package:flutter/material.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedRectangle84Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup42Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup44Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedProductsWidget1.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup47Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/Generated303Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup46Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup48Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup43Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup45Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax6widget/generated/GeneratedGroup49Widget.dart';

/* Frame iPhone 13 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 5, 56, 128),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 616.0,
                              child: GeneratedRectangle84Widget(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 29.0,
                              child: GeneratedProductsWidget1(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 82.0,
                              child: GeneratedGroup42Widget(),
                            ),
                            Positioned(
                              left: 138.0,
                              top: 74.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 24.0,
                              child: Generated303Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup43Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 420.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup44Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 500.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup45Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup46Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 660.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup47Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup48Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 80.0,
                              child: GeneratedGroup49Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
