import 'package:flutter/material.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedGroup4Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedDolibarrWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedLoginWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedVectorWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedRectangle2Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedRectangle3Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedUsersvgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedUndraw_learning_re_32qv1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedMobileWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedUsernameWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedUrlWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedRectangle4Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedLocksvgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax2widget/generated/GeneratedBysigninginyouagreetoourtermsandconditionsWidget.dart';

/* Frame iPhone 13 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 61.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 761.0,
                              right: null,
                              bottom: null,
                              width: 305.0,
                              height: 61.0,
                              child: GeneratedGroup4Widget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 475.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 61.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 373.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 61.0,
                              child: GeneratedRectangle4Widget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 334.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 44.0,
                              child: GeneratedDolibarrWidget(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 363.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 22.0,
                              child: GeneratedMobileWidget(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 674.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 34.0,
                              child:
                                  GeneratedBysigninginyouagreetoourtermsandconditionsWidget(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedVectorWidget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedUrlWidget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 509.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 24.0,
                              child: GeneratedUsernameWidget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 609.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 24.0,
                              child: GeneratedLoginWidget(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 109.0,
                              right: null,
                              bottom: null,
                              width: 297.0,
                              height: 176.0,
                              child: GeneratedUndraw_learning_re_32qv1Widget(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedLocksvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 510.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedUsersvgrepocom1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
