import 'package:flutter/material.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedInfocirclesvgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedGroup41Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedLogoutWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedHelpWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedCompanyinfoWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedEllipse1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedGroup40Widget1.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedFatouSkuljiWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedCrosssvgrepocom11Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedStar1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedChangeProfileWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/Generated020720230508PMWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedLine1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedLogoutsvgrepocom11Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax5widget/generated/GeneratedConntectedsinceWidget.dart';

/* Frame iPhone 13 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 257.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 18.0,
                              child: GeneratedConntectedsinceWidget(),
                            ),
                            Positioned(
                              left: 274.0,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedStar1Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 1.0,
                              child: GeneratedLine1Widget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 110.0,
                              child: GeneratedEllipse1Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 26.0,
                              child: GeneratedFatouSkuljiWidget(),
                            ),
                            Positioned(
                              left: 140.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 149.0,
                              height: 19.0,
                              child: Generated020720230508PMWidget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 553.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 22.0,
                              child: GeneratedLogoutWidget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 19.0,
                              child: GeneratedCompanyinfoWidget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedInfocirclesvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 19.0,
                              child: GeneratedChangeProfileWidget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 22.0,
                              child: GeneratedHelpWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 424.0,
                              right: null,
                              bottom: null,
                              width: 23.333330154418945,
                              height: 23.333330154418945,
                              child: GeneratedGroup40Widget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 487.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedGroup41Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 550.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedLogoutsvgrepocom11Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedCrosssvgrepocom11Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
