import 'package:flutter/material.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse7Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse5Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse9Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse2Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse6Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse8Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax7widget/generated/GeneratedEllipse3Widget.dart';

/* Frame iPhone 13 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 59.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse2Widget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 203.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse5Widget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse7Widget(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse8Widget(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse9Widget(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 59.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse6Widget(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 203.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse3Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
