import 'package:flutter/material.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedPeoplesvgrepocom11Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedBuilding2svgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedModulesWidget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup39Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup33Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup36Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup34Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedToolssvgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup32Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroupWidget13.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup31Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedMenuburgersvgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup40Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedSalesupgraphsvgrepocom1Widget.dart';
import 'package:dolibarr_mobile/dolibarr_mobileapp/generatediphone13promax4widget/generated/GeneratedGroup38Widget.dart';

/* Frame iPhone 13 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 157.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 29.0,
                              child: GeneratedModulesWidget(),
                            ),
                            Positioned(
                              left: 167.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 38.0,
                              child: GeneratedGroup38Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedMenuburgersvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 589.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup34Widget(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 589.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup39Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 398.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup32Widget(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 207.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup31Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup36Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 207.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup40Widget(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 398.0,
                              right: null,
                              bottom: null,
                              width: 126.0,
                              height: 126.0,
                              child: GeneratedGroup33Widget(),
                            ),
                            Positioned(
                              left: 283.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedBuilding2svgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedToolssvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 283.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedPeoplesvgrepocom11Widget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 31.103748321533203,
                              height: 37.999813079833984,
                              child: GeneratedGroupWidget13(),
                            ),
                            Positioned(
                              left: 283.0,
                              top: 618.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedSalesupgraphsvgrepocom1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
